[build]
command = "npm run build"
publish = "dist"

[build.environment]
GO_VERSION = "1.19"         # Satisfy Netlify's Go requirement
NODE_VERSION = "18"         # Use Node 18 or your preferred version
